name: Generate Compatibility Report

on:
  push:
    branches:
      - '*'
jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: jpd002/PlayServices
        ref: develop
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build
    - name: Run
      run: dotnet run -p tools/CompatibilityValidator
      env:
        ps_gh_apitoken: ${{ secrets.GITHUB_TOKEN }}
        ps_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        ps_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
