name: Generate Compatibility Report

on:
  push:
    branches:
      - '*'
jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: jpd002/PlayServices
        ref: develop
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build
    - name: Run
      run: dotnet run -p tools/CompatibilityValidator
